### ISSUE TITLE
To incorporate lagged values of response variable

### ISSUE THREAD

**Issue by dmresearch15** [bonheurgirl/Forecasting-in-R#1]
Enjoyed with the steps you’ve adopted.

Interested to add lagged values (say, lag = 3) of response variable actualsales in the model. To do that, what’re the modifications one needs to make in the historical data set postit as well as in the explanatory_data. Any other modification elsewhere in the program is needed or not.

**Comment by anita-owens** [comment]
Thanks for your question. I just want to be sure I understand that you want to add lagged sales to your dataframe and then predict y (actual sales) and y_lag (actual sales n=3)?

![Screen Shot 2022-10-14 at 9 24 46 PM](https://user-images.githubusercontent.com/13710429/195926302-dd5779e0-d715-4a34-b3b1-38990b12a908.png)

**Comment by dmresearch15** [comment]
Thanks for your quick response.

You’re right. 

Interested to forecast actualsales (response variable) using it’s lagged values (say, lag = 3) and explanatory variables.

Say, Forecast_Horizon = 12.

I’m assuming that, I’ve data for explanatory variables for the period historical + Forecast_Horizon.

As I’m using lagged values of actualsales, my idea is:

Step 1: Model forecast actualsales at h = 1

Step 2: Then one needs to utilise forecast value of actualsales at h = 1, because It is needed to recalculate lagged values of actualsales.

Step 3: Continue till h = 12

Step 4: Like to plot historical and forecast values with say, 95% confidence limits.

**Comment by anita-owens** [comment]
If I’m understanding correctly, your main challenge will be dealing with missing values and also shifting the values of your explanatory variables (e.g price & display), but this can be dealt with. Using lagged y variable as an explanatory variable is pretty straight-forward as outlined in this example in Hyman’s book https://otexts.com/fpp3/lagged-predictors.html as this makes sense as advertising can have a lagged effect on sales. It sounds like from your description, that your sales have a lagged effect.

Also, have you also looked at a recursive forecasting method which Modeltime does support? Your lagged predicted values become features in the model as outlined in the documentation: https://business-science.github.io/modeltime.ensemble/articles/recursive-ensembles.html. The example shown  is pretty easy to follow and could fit your use case.

It might be good to start off with a basic linear regression model and compare the coefficients. Your coefficients will tell you if your predictors have an immediate or lagged effect and help you decide what is useful to include in your forecast model. I don’t know if I’ve provided any help here, but this is how I would approach the task.

**Comment by dmresearch15** [comment]
Thanks for your quick response. I'll go through the information you've provided to me.

**Comment by anita-owens** [comment]
You're welcome. Kaggle also has a Time Series tutorial that is quite good. It's done in Python, but I tried the [lagged module](https://www.kaggle.com/code/ryanholbrook/time-series-as-features) this morning and it really does a good job of using lagged plots & correlograms to determine if any of the lags are significant based on promotional effect. 

https://www.kaggle.com/code/anitaowens/forecasting-lagged-variables-in-python. 

If you are comfortable with Python this might be worth checking out.
